<a href="https://colab.research.google.com/github/Mukheshkrishna/Basic-ML/blob/main/Logistic_Regression_iris_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [4]:
#get data directly from scikit-learn
X, y = load_iris(return_X_y=True)

In [5]:
X.shape , y.shape

((150, 4), (150,))

In [6]:
X[0] , y[0]

(array([5.1, 3.5, 1.4, 0.2]), 0)

In [7]:
np.unique(y)

array([0, 1, 2])

In [8]:
#split the data
X_train, X_test, y_train, y_test =\
    train_test_split(X, y, test_size=0.2, random_state=0)

In [9]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([6.4, 3.1, 5.5, 1.8]), 4.2, 1.8371173070873836)

In [10]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

In [11]:
X_train[0], np.mean(X_train[0]), np.std(X_train[0])

(array([0.61303014, 0.10850105, 0.94751783, 0.736072  ]),
 0.601280253757793,
 0.308633549281788)

In [14]:
#create a model and train it
model = LogisticRegression(C=0.05, multi_class='ovr',random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0)

In [15]:
#evaluate the model
X_test = scaler.transform(X_test)
y_pred = model.predict(X_test)


In [16]:
model.score(X_train, y_train)

0.8666666666666667

In [17]:
model.score(X_test, y_test)

0.7333333333333333

In [18]:
confusion_matrix(y_test, y_pred)

array([[11,  0,  0],
       [ 0,  5,  8],
       [ 0,  0,  6]])

In [19]:
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.38      0.56        13
           2       0.43      1.00      0.60         6

    accuracy                           0.73        30
   macro avg       0.81      0.79      0.72        30
weighted avg       0.89      0.73      0.73        30

